SELECT * FROM BALKANVIBEZ;
DROP TABLE IF EXISTS WORKSPACE;
DROP TABLE IF EXISTS PLAYSTATION_CLOUD;
DROP TABLE IF EXISTS DRAGANAMIRKOVIC;
DROP TABLE if exists BALKANVIBEZ;

CREATE TABLE WORKSPACE (
ID INT NOT NULL,
AUFRÄUMEN VARCHAR(45)
);

CREATE TABLE PLAYSTATION_CLOUD (
ABONNEMENT VARCHAR(45)
);

CREATE TABLE BALKANVIBEZ (
SEEPARKSAAL VARCHAR(45),
TICKET VARCHAR(45)
);

-- INSERT INTO BALKANVIBEZ(SEEPARKSAAL, TICKET) VALUES ("1","35CHF");
-- INSERT INTO BALKANVIBEZ(SEEPARKSAAL, TICKET) VALUES ("2", "85CHF");
